const auth = require("./auth");
const user = require("./user");
const role = require("./role");
const color = require("./color");
const size = require("./size");
const material = require("./material");
const discount = require("./discount");
const gender = require("./gender");
const groupCategory = require("./groupCategory");
const category = require("./category");
const product = require("./product");
const productDetail = require("./productDetail");
const cart = require("./cart");
const cartItem = require("./cartItem");
const order = require("./order");
const coupon = require("./coupon");
const orderStatus = require("./orderStatus");
const orderItem = require("./orderItem");
const image = require("./image");
const statistics = require("./statistics");
const configRoute = (app) => {
  app.use("/v1/api/auth", auth);
  app.use("/v1/api/user", user);
  app.use("/v1/api/role", role);
  app.use("/v1/api/color", color);
  app.use("/v1/api/size", size);
  app.use("/v1/api/discount", discount);
  app.use("/v1/api/material", material);
  app.use("/v1/api/gender", gender);
  app.use("/v1/api/group-category", groupCategory);
  app.use("/v1/api/category", category);
  app.use("/v1/api/product", product);
  app.use("/v1/api/product-detail", productDetail);
  app.use("/v1/api/cart", cart);
  app.use("/v1/api/cart-item", cartItem);
  app.use("/v1/api/order-item", orderItem);
  app.use("/v1/api/order", order);
  app.use("/v1/api/order-status", orderStatus);
  app.use("/v1/api/coupon", coupon);
  app.use("/v1/api/image", image);
  app.use("/v1/api/statistics", statistics);
};
module.exports = configRoute;
