const auth = require("./auth");
const user = require("./user");
const role = require("./role");
const color = require("./color");
const size = require("./size");
const material = require("./material");
const discount = require("./discount");
const gender = require("./gender");
const groupCategory = require("./groupCategory");
const category = require("./category");
const product = require("./product");
const productDetail = require("./productDetail");
const cart = require("./cart");
const cartItem = require("./cartItem");
const order = require("./order");
const coupon = require("./coupon");
const orderStatus = require("./orderStatus");
const orderItem = require("./orderItem");
const image = require("./image");
const statistics = require("./statistics");
const upload = require("./upload");
const productMaterial = require("./productMaterial");
const comment = require("./comment");
const repliedComment = require("./repliedComment");
const productUser = require("./productUser");
const banner = require("./banner");
const notification = require("./notification");
const discountCategory = require("./discountCategory");
const sizeGuide = require("./sizeGuide");
const configRoute = (app) => {
  app.use("/api/auth", auth);
  app.use("/api/user", user);
  app.use("/api/role", role);
  app.use("/api/color", color);
  app.use("/api/size", size);
  app.use("/api/size-guide", sizeGuide);
  app.use("/api/discount", discount);
  app.use("/api/material", material);
  app.use("/api/gender", gender);
  app.use("/api/group-category", groupCategory);
  app.use("/api/category", category);
  app.use("/api/product", product);
  app.use("/api/product-detail", productDetail);
  app.use("/api/cart", cart);
  app.use("/api/cart-item", cartItem);
  app.use("/api/order-item", orderItem);
  app.use("/api/order", order);
  app.use("/api/order-status", orderStatus);
  app.use("/api/product-material", productMaterial);
  app.use("/api/coupon", coupon);
  app.use("/api/image", image);
  app.use("/api/statistics", statistics);
  app.use("/api/upload", upload);
  app.use("/api/comment", comment);
  app.use("/api/replied-comment", repliedComment);
  app.use("/api/product-user", productUser);
  app.use("/api/banner", banner);
  app.use("/api/notification", notification);
  app.use("/api/discount-category", discountCategory);
};
module.exports = configRoute;
